language: node_js

node_js:
   - node

env:
  global:
    - GET_ENV_VAR=./.travis/get_env_specific_value.sh
    - FIREBASE_PROJECT=$($GET_ENV_VAR development production)

branches:
   only:
      - master
      - develop

before_script:
   - npm install -g firebase-tools
   - npm install -g @angular/cli

script:
   - npm run-script build --prod --aot

after_success:
   - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
   - firebase deploy --token $FIREBASE_TOKEN
